routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Livewire\Category\MenuCategory;
use App\Http\Controllers\Auth\AdminLoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/all-clear', function () {
    Artisan::call('config:clear');
    Artisan::call('cache:clear');
    Artisan::call('config:cache');
    Artisan::call('optimize:clear');
    Artisan::call('storage:link');
    return 'CACHE CONFIG CLEARED';
});

Route::namespace('Frontend')->group(function () {
    Route::get('/', 'MainController@index')->name('front.home');
//    Route::get('/about', 'MainController@about')->name('front.about');
    Route::get('/gallery', 'MainController@gallery')->name('front.gallery');
    Route::get('/newsletter', 'MainController@newsletter')->name('front.newsletter');
    Route::get('/contact', 'MainController@contact')->name('front.contact');
    Route::post('/contact/enquiry', 'MainController@enquiryMail')->name('front.contact.enquiry');

    Route::get('/{slug}', 'MainController@categoryPages')->name('front.page.content');
    //resources section
    Route::get('/resources/{slug}', 'MainController@resourcesBranch')->name('front.resources.branch');

});


//Admin Profile Section
Route::group(['prefix' => 'backend/system', 'as' => 'admin.'], function () {
    Route::get('/login', [AdminLoginController::class, 'showLoginForm'])->name('login');
    Route::post('/login/validate', [AdminLoginController::class, 'login'])->name('login.submit');
    Route::get('/forget-password', [AdminLoginController::class, 'showForgetPasswordForm'])->name('forget.password');
    Route::get('/logout', [AdminLoginController::class, 'logout'])->name('logout');
});

Route::group(['middleware' => ['auth']], function () {
    Route::namespace('Backend')->group(function () {
        Route::group(['prefix' => 'backend/system'], function () {

            Route::group(['prefix' => 'dashboard'], function () {
                Route::get('/', 'MainController@index')->name('dashboard');
            });

            Route::group(['prefix' => 'category'], function () {
                Route::get('/{menu}', 'MenuCategoryController@index')->name('menu.category');
                Route::get('/{menu}/edit/{id}', 'MenuCategoryController@index')->name('menu.category.edit');
                Route::get('/{menu}/{slug}/{id}', 'MenuCategoryController@show')->name('menu.category.show');

                Route::post('/delete', 'MenuCategoryController@destroy')->name('menu.category.delete');
                Route::post('/update/{id}', 'MenuCategoryController@update')->name('menu.category.update');
            });

            Route::group(['prefix' => 'about'], function () {
                Route::get('/', 'AboutController@index')->name('about');
            });

            Route::group(['prefix' => 'church-ministries'], function () {
                Route::get('/', 'ChurchMinistryController@index')->name('ministries');
            });

            Route::group(['prefix' => 'meeting-time'], function () {
                Route::get('/', 'MeetingController@index')->name('meeting');
            });

            Route::group(['prefix' => 'hgst'], function () {
                Route::get('/', 'HgstController@index')->name('hgst');
            });

            Route::group(['prefix' => 'resources'], function () {
                Route::get('/', 'ResourceController@index')->name('resources');

                //resources category
                Route::get('/{slug}/{id}', 'ResourceController@details')->name('resources.category.details');
                Route::get('/{slug}/{id}/add', 'ResourceController@addResources')->name('resources.category.resources.add');
                Route::post('/{slug}/{id}/store', 'ResourceController@storeBranches')->name('resources.category.resources.store');
                Route::get('/{category}/{slug}/{id}/edit', 'ResourceController@editResources')->name('resources.category.resources.edit');
                Route::post('/{branch_id}/update', 'ResourceController@updateBranches')->name('resources.category.resources.update');

                //name-of-resource-slug/unique-id'
                Route::get('/name-of-resource-slug/25145', 'ResourceController@show')->name('resources.show');
            });

            Route::group(['prefix' => 'gallery'], function () {
                Route::get('/', 'GalleryController@index')->name('gallery');
            });

            Route::group(['prefix' => 'verse'], function () {
                Route::get('/', 'VerseController@index')->name('verse');
            });

            Route::group(['prefix' => 'leader'], function () {
                Route::get('/', 'LeaderController@index')->name('leader');
            });

            Route::group(['prefix' => 'news'], function () {
                Route::get('/', 'NewsController@index')->name('news');
                Route::get('/add', 'NewsController@create')->name('news.events.add');
                Route::post('/store', 'NewsController@store')->name('news.events.store');
                Route::get('/edit/{id}', 'NewsController@edit')->name('news.events.edit');
                Route::post('/update/{id}', 'NewsController@update')->name('news.events.update');
            });

            Route::group(['prefix' => 'testimonials'], function () {
                Route::get('/', 'TestimonialController@index')->name('testimonials');
            });

            Route::group(['prefix' => 'system-config'], function () {
                Route::get('/', 'SystemConfigurationController@index')->name('system.config');
            });

            // for sitemap auto generation from admin section only.
            Route::get('/generate-sitemap', function () {
                Artisan::call('sitemap:generate');
                return 'Sitemap Created Successfully'; //Return anything
            })->name('sitemap.generate');

            Route::group(['prefix' => 'db-backup'], function () {
                Route::get('/', 'MainController@dispayData')->name('db.backup');
                Route::get('/generate', 'MainController@exportBackup')->name('db.backup.generate');
                Route::get('download/{filename}', 'MainController@downloadFile')->name('db.backup.dowload');
            });

            //for db backup generation.
            Route::get('/backup', function () {
                Artisan::call('db:backup');
                return 'DATABASE BACKUP CREATED';
            })->name('backup.generate');

        });
    });
    Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
        \UniSharp\LaravelFilemanager\Lfm::routes();
    });
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Backend/AboutController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\MenuItemCategory;
use Illuminate\Http\Request;

class AboutController extends Controller
{
    private $_page='about.';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data=MenuItemCategory::where('main_menu','about')->orderBy('created_at','desc')->get();
        return $this->returnBackendView($this->_page . 'index', ['page_title' => 'About Us','data'=>$data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/ChurchMinistryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\MenuItemCategory;
use Illuminate\Http\Request;

class ChurchMinistryController extends Controller
{
    private $_page = 'ministries.';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = MenuItemCategory::where('main_menu', 'church')->orderBy('created_at', 'desc')->get();
        return $this->returnBackendView($this->_page . 'index', ['page_title' => 'Church Ministries', 'data' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/GalleryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class GalleryController extends Controller
{
    private $_page = 'gallery.';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return $this->returnBackendView($this->_page . 'index', ['page_title' => 'Gallery']);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/HgstController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\MenuItemCategory;
use Illuminate\Http\Request;

class HgstController extends Controller
{
    private $_page = 'hgst.';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = MenuItemCategory::where('main_menu', 'hgst')->orderBy('created_at', 'desc')->get();
        return $this->returnBackendView($this->_page . 'index', ['page_title' => 'HGST', 'data' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/LeaderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class LeaderController extends Controller
{
    private $_page = 'leaders.';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return $this->returnBackendView($this->_page . 'index', ['page_title' => 'Leaders']);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/MainController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\DbBackup;
use Carbon\Carbon;
use App\Http\Requests;
use Illuminate\Support\Str;

class MainController extends Controller
{

    public function index()
    {
        return $this->returnBackendView('dashboard', ['page_title' => 'Dashboard']);
    }

    public function dispayData()
    {
        $data = DbBackup::latest()->get();
        return $this->returnBackendView('db-backup', ['page_title' => 'DB Backup', 'data' => $data]);
    }

    public function exportBackup()
    {
        $filename = "db-backup-" . Str::uuid() . '-' . Carbon::now()->format('Y-m-d') . ".gz";
        $command = "mysqldump --column-statistics=0 --user=" . env('DB_USERNAME') . " --password=" . env('DB_PASSWORD') . " --host=" . env('DB_HOST') . " " . env('DB_DATABASE') . "  | gzip > " . storage_path() . "/app/public/backup/" . $filename;
        $returnVar = NULL;
        $output = NULL;
        exec($command, $output, $returnVar);
        DbBackup::create([
            'file_name' => $filename
        ]);
        return redirect()->back()->with(['message' => 'DB backup successfully created']);
    }

    function downloadFile($filename)
    {
        $file = public_path('storage/backup/') . $filename;
        return response()->download($file);
    }
}

resources/views/Backend/includes/header-panel.blade.php
<!-- Header -->
<header id="page-header">
    <!-- Header Content -->
    <div class="content-header">
        <!-- Left Section -->
        <div class="d-flex align-items-center">
            <!-- Toggle Sidebar -->
            <button type="button" class="btn btn-sm btn-dual mr-2 d-lg-none" data-toggle="layout"
                    data-action="sidebar_toggle">
                <i class="fa fa-fw fa-bars"></i>
            </button>
            <!-- END Toggle Sidebar -->

            <!-- Toggle Mini Sidebar -->
            <button type="button" class="btn btn-sm btn-dual mr-2 d-none d-lg-inline-block" data-toggle="layout"
                    data-action="sidebar_mini_toggle">
                <i class="fa fa-fw fa-ellipsis-v"></i>
            </button>
            <!-- END Toggle Mini Sidebar -->
        </div>
        <!-- END Left Section -->

    {{--        {{ dd(Auth::user()->userDetails) }}--}}

    <!-- Right Section -->
        <div class="d-flex align-items-center">
            <!-- User Dropdown -->
            <div class="dropdown d-inline-block ml-2">
                <button type="button" class="btn btn-sm btn-dual d-flex align-items-center"
                        id="page-header-user-dropdown" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                    {{--<img class="rounded-circle"--}}
                         {{--@if(Auth::user()->userDetails->avatar!='')--}}
                         {{--src="{{ asset(Auth::user()->userDetails->avatar ) }}"--}}
                         {{--@else--}}
                         {{--src="{{ asset('assets/backend/assets/media/avatars/avatar13.jpg') }}"--}}
                         {{--@endif--}}
                         {{--alt="{{ Auth::user()->userDetails->name ? Auth::user()->userDetails->name:'Account Photo' }}"--}}
                         {{--width="25px">--}}
                    <?php
//                    $name = Auth::user()->userDetails->name;
//                    $firstName = explode(' ', trim($name));
                    ?>
                    {{--<span class="d-none d-sm-inline-block ml-2">{{ $firstName[0] }}</span>--}}
                    <i class="fa fa-fw fa-angle-down d-none d-sm-inline-block ml-1 mt-1"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-md dropdown-menu-right p-0 border-0"
                     aria-labelledby="page-header-user-dropdown">
                    {{--<div class="p-3 text-center bg-primary-dark rounded-top">--}}
                        {{--<img class="img-avatar img-avatar48 img-avatar-thumb"--}}
                             {{--@if(Auth::user()->userDetails->avatar!='')--}}
                             {{--src="{{ asset(Auth::user()->userDetails->avatar ) }}"--}}
                             {{--@else--}}
                             {{--src="{{ asset('assets/backend/assets/media/avatars/avatar13.jpg') }}"--}}
                             {{--@endif--}}
                             {{--alt="{{ Auth::user()->userDetails->name ? Auth::user()->userDetails->name:'Account Photo' }}">--}}
                        {{--<p class="mt-2 mb-0 text-white font-w500">{{ Auth::user()->userDetails->name }}</p>--}}
                        {{--<p class="mb-0 text-white-50 font-size-sm">{{ Auth::user()->userDetails->userRole->name }}</p>--}}
                    {{--</div>--}}
                    <div class="p-2">
                        {{--<a class="dropdown-item d-flex align-items-center justify-content-between"--}}
                           {{--href="{{ route('profile') }}">--}}
                            {{--<span class="font-size-sm font-w500">Profile</span>--}}
                        {{--</a>--}}
                        {{--<a class="dropdown-item d-flex align-items-center justify-content-between"--}}
                        {{--href="">--}}
                        {{--<span class="font-size-sm font-w500">Settings</span>--}}
                        {{--</a>--}}
                        <div role="separator" class="dropdown-divider"></div>

                        {{--<a class="dropdown-item d-flex align-items-center justify-content-between"--}}
                           {{--href="{{ route('admin.logout') }}">--}}
                            {{--<span class="font-size-sm font-w500">Log Out</span>--}}
                        {{--</a>--}}
                    </div>
                </div>
            </div>
            <!-- END User Dropdown -->
        </div>
        <!-- END Right Section -->
    </div>
    <!-- END Header Content -->

    <!-- Header Search -->
    <div id="page-header-search" class="overlay-header bg-white">
        <div class="content-header">
            <form class="w-100" action="be_pages_generic_search.html" method="POST">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
                        <button type="button" class="btn btn-alt-danger" data-toggle="layout"
                                data-action="header_search_off">
                            <i class="fa fa-fw fa-times-circle"></i>
                        </button>
                    </div>
                    <input type="text" class="form-control" placeholder="Search or hit ESC.."
                           id="page-header-search-input" name="page-header-search-input">
                </div>
            </form>
        </div>
    </div>
    <!-- END Header Search -->

    <!-- Header Loader -->
    <!-- Please check out the Loaders page under Components category to see examples of showing/hiding it -->
    <div id="page-header-loader" class="overlay-header bg-white">
        <div class="content-header">
            <div class="w-100 text-center">
                <i class="fa fa-fw fa-circle-notch fa-spin"></i>
            </div>
        </div>
    </div>
    <!-- END Header Loader -->
</header>
<!-- END Header -->

resources/views/Backend/includes/nav-panel.blade.php
<div id="page-container"
     class="sidebar-o sidebar-dark enable-page-overlay side-scroll page-header-fixed main-content-narrow">

    <nav id="sidebar" aria-label="Main Navigation">
        <!-- Side Header -->
        <div class="content-header bg-white-5">
            <!-- Logo -->
            <a class="font-w600 text-dual" href="{{ route('dashboard') }}">
                <span class="smini-visible"><i class="fa fa-circle-notch text-primary"></i></span>
                <span class="smini-hide font-size-h5 tracking-wider">
                    Himalayan<span class="font-w400"> Church</span>
                </span>
            </a>
            <!-- END Logo -->
            <div>
                <button type="button" class="d-lg-none ml-1 btn btn-dual btn-sm" data-toggle="layout"
                        data-action="sidebar_close">
                    <i class="fa fa-fw fa-times"></i>
                </button>
            </div>
        </div>
        <!-- END Side Header -->

        <!-- Sidebar Scrolling -->
        <div class="js-sidebar-scroll">
            <!-- Side Navigation -->
            <div class="content-side">
                <ul class="nav-main">
                    <li class="nav-main-item">
                        <a class="nav-main-link {{ (request()->is('backend/system/dashboard','backend/system/dashboard/*')) ? 'active' : '' }}"
                           href="{{ route('dashboard') }}">
                            <i class="nav-main-link-icon fa fa-home"></i>
                            <span class="nav-main-link-name">Dashboard</span>
                        </a>
                    </li>
                    <li class="nav-main-item">
                        <a class="nav-main-link {{ (request()->is('backend/system/about','backend/system/about/*','backend/system/category/about','backend/system/category/about/*')) ? 'active' : '' }}"
                           href="{{ route('about') }}">
                            <i class="nav-main-link-icon fa fa-adn"></i>
                            <span class="nav-main-link-name">About</span>
                        </a>
                    </li>
                    <li class="nav-main-item">
                        <a class="nav-main-link {{ (request()->is('backend/system/church-ministries','backend/system/church-ministries/*','backend/system/category/church','backend/system/category/church/*')) ? 'active' : '' }}"
                           href="{{ route('ministries') }}">
                            <i class="nav-main-link-icon fa fa-fort-awesome"></i>
                            <span class="nav-main-link-name">Church Ministries</span>
                        </a>
                    </li>
                    <li class="nav-main-item">
                        <a class="nav-main-link {{ (request()->is('backend/system/meeting-time','backend/system/meeting-time/*','backend/system/category/meeting','backend/system/category/meeting/*')) ? 'active' : '' }}"
                           href="{{ route('meeting') }}">
                            <i class="nav-main-link-icon fa fa-linode"></i>
                            <span class="nav-main-link-name">Meeting Time</span>
                        </a>
                    </li>
                    <li class="nav-main-item">
                        <a class="nav-main-link {{ (request()->is('backend/system/hgst','backend/system/hgst/*','backend/system/category/hgst','backend/system/category/hgst/*')) ? 'active' : '' }}"
                           href="{{ route('hgst') }}">
                            <i class="nav-main-link-icon fa fa-linode"></i>
                            <span class="nav-main-link-name">HGST</span>
                        </a>
                    </li>
                    <li class="nav-main-item">
                        <a class="nav-main-link {{ (request()->is('backend/system/resources','backend/system/resources/*','backend/system/category/resource','backend/system/category/resource/*')) ? 'active' : '' }}"
                           href="{{ route('resources') }}">
                            <i class="nav-main-link-icon fa fa-linode"></i>
                            <span class="nav-main-link-name">Resources</span>
                        </a>
                    </li>
                    <li class="nav-main-item">
                        <a class="nav-main-link {{ (request()->is('backend/system/gallery','backend/system/gallery/*')) ? 'active' : '' }}"
                           href="{{ route('gallery') }}">
                            <i class="nav-main-link-icon fa fa-image"></i>
                            <span class="nav-main-link-name">Gallery</span>
                        </a>
                    </li>
                    <li class="nav-main-item">
                        <a class="nav-main-link {{ (request()->is('backend/system/verse','backend/system/verse/*')) ? 'active' : '' }}"
                           href="{{ route('verse') }}">
                            <i class="nav-main-link-icon fa fa-tag"></i>
                            <span class="nav-main-link-name">Verse of Day</span>
                        </a>
                    </li>
                    <li class="nav-main-item">
                        <a class="nav-main-link {{ (request()->is('backend/system/leader','backend/system/leader/*')) ? 'active' : '' }}"
                           href="{{ route('leader') }}">
                            <i class="nav-main-link-icon fa fa-user-secret"></i>
                            <span class="nav-main-link-name">Leaders</span>
                        </a>
                    </li>
                    <li class="nav-main-item">
                        <a class="nav-main-link {{ (request()->is('backend/system/news','backend/system/news/*')) ? 'active' : '' }}"
                           href="{{ route('news') }}">
                            <i class="nav-main-link-icon fa fa-newspaper"></i>
                            <span class="nav-main-link-name">News</span>
                        </a>
                    </li>
                    <li class="nav-main-item">
                        <a class="nav-main-link {{ (request()->is('backend/system/testimonials','backend/system/testimonials/*')) ? 'active' : '' }}"
                           href="{{ route('testimonials') }}">
                            <i class="nav-main-link-icon fa fa-comment"></i>
                            <span class="nav-main-link-name">Testimonials</span>
                        </a>
                    </li>
                    <li class="nav-main-item">
                        <a class="nav-main-link" href="{{ route('system.config') }}">
                            <i class="nav-main-link-icon fa fa-cogs"></i>
                            <span class="nav-main-link-name">System Configuration</span>
                        </a>
                    </li>
                    <li class="nav-main-item">
                        <a class="nav-main-link" target="_blank" href="{{ route('sitemap.generate') }}">
                            <i class="nav-main-link-icon fa fa-link"></i>
                            <span class="nav-main-link-name">Generate Sitemap</span>
                        </a>
                    </li>
                    <li class="nav-main-item">
                        <a class="nav-main-link" href="{{ route('db.backup') }}">
                            <i class="nav-main-link-icon fa fa-database"></i>
                            <span class="nav-main-link-name">Export DB Backup</span>
                        </a>
                    </li>
                    <li class="nav-main-item">
                        <a class="nav-main-link" href="{{ route('admin.logout') }}">
                            <i class="nav-main-link-icon fa fa-power-off text-danger"></i>
                            <span class="nav-main-link-name">Logout</span>
                        </a>
                    </li>

                </ul>
            </div>
            <!-- END Side Navigation -->
        </div>
        <!-- END Sidebar Scrolling -->
    </nav>
    <!-- END Sidebar -->